== Unidade B: Introdução à modelagem de sistemas usando UML

:img: images/modelagem

:atividade: https://raw.githubusercontent.com/edusantana/analise-e-projeto-sistemas-livro/{edition}/atividades/cap2-atividades.docx

.Objetivos
____

Ao final desta unidade (B), você deverá se capaz de:


1. *Entender* o que é um modelo e modelagem de sistemas, *exemplificando* modelos do seu cotidiano e o processo de modelagem.

2. *Lembrar* o que é UML, *reconhecendo* o propósito de UML.

3. *Entender* o que é um diagrama, *classificando* de um conjunto de representações quais são diagramas.

4. *Entender* o versionamento da linguagem UML, *julgando* afirmações sobre o versionamento de UML.

5. *Lembrar* das visões de sistemas, *identificando* as características das visões.

6. *Utilizar* uma ferramenta de UML, *instalando* e *executando* uma ferramenta UML.

____

.Elementos de organização prévia
****

- Para realizar os estudos deste capítulo você precisará do livro
_Análise e Projeto de Sistemas de Informação Orientados a Objetos_.

- Para realizar as atividades desta capítulo no computador
baixe o aquivo https://github.com/edusantana/analise-e-projeto-sistemas-livro/raw/master/atividades/cap2-atividades.docx[cap2-atividades.docx] acessando http://goo.gl/A2A7hG.

- Na última seção do capítulo será solicitado que você baixe e 
instale uma ferramenta UML. Caso você tenha uma conexão lenta com a
internet, recomendamos que comece pela
+++<xref linkend="sec_uml_ferramentas" 
xrefstyle="select: label pageabbrev quotedtitle"/>+++. Escolha uma
ferramenta e deixe fazendo o download enquanto estuda as demais seções.

****

include::guia-unidadeB-objetivo1.adoc[]

include::guia-unidadeB-objetivo2.adoc[]

include::guia-unidadeB-objetivo3.adoc[]

include::guia-unidadeB-objetivo4.adoc[]

include::guia-unidadeB-objetivo5.adoc[]

include::guia-unidadeB-objetivo6.adoc[]

